swagger: 2.0
info:
  title: Cell Tower Geolocation
  description: This is a cell tower geolocation converter on the OpenAPI 3.0 specification.
  version: 0.1.0
tags:
  - name: Coordinates
paths:
  /wgs84/encode:
    post:
      tags:
        - Coordinates
      summary: WGS84 encode endpoint
      description: World Geodetic System 1984
      operationId: encodeWGS84
      requestBody:
        description: Encode WGS84
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WGS84_decoded'
      parameters:
        - name: latitude
          required: true
          in: query
          schema:
            type: number
        - name: longitude
          required: true
          in: query
          schema:
            type: number
        - name: innerRadiuse
          in: query
          schema:
            type: number
        - name: uncertaintyRadiuse
          in: query
          schema:
            type: number
        - name: offsetAngle
          in: query
          schema:
            type: number
        - name: includedAngle
          in: query
          schema:
            type: number
        - name: confidence
          in: query
          schema:
            type: number
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WGS84_encoded'
        '405':
          description: Invalid input
  /wgs84/decode:
    post:
      tags: 
        - Coordinates
      summary: WGS84 decode endpoint
      description: World Geodetic System 1984
      operationId: decodeWGS84
      requestBody:
        description: Decode WGS84
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WGS84_encoded'
      parameters:
        - name: wgs84
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WGS84_decoded'
        '405':
          description: Invalid input
components:
  schemas:
    WGS84_encoded:
      required:
        - wgs84
      type: object
      properties:
        wgs84:
          type: string
          example: 'A0 49 41 81 FF E8 B1 00 09 12 18 18 32'
    WGS84_decoded:
      required:
        - latitude
        - longitude
      type: object
      properties:
        latitude:
          type: number
          example: 12.2324125
          description: 'from -90 to +90 [degrees]'
        longitude:
          type: number
          example: 47.2324125
          description: 'from -180 to +180 [degrees]'
        innerRadiuse:
          type: number
          example: 60
          description: 'increment of 5 from 0 to 327 675 [meters]'
        uncertaintyRadiuse:
          type: number
          example: 20
          description: 'from 0 to 1 800 000 [meters]'
        offsetAngle:
          type: number
          example: 50
          description: 'increment of 2 from 0 to 359.9...9 [degrees]'
        includedAngle:
          type: number
          example: 30
          description: 'increment of 2 from 0.0...1 to 360 [degrees]'
        confidence:
          type: number
          example: 90