---
swagger: "2.0"
info:
  description: "This is a cell tower geolocation converter on the OpenAPI 3.0 specification."
  version: "0.1.0"
  title: "Cell Tower Geolocation"
host: "localhost:33999"
tags:
- name: "Coordinates"
paths:
  /wgs84/encode:
    post:
      tags:
      - "Coordinates"
      summary: "WGS84 encode endpoint"
      description: "World Geodetic System 1984"
      operationId: "encodeWGS84"
      parameters: []
      responses:
        "200":
          description: "Successful operation"
          x-responseId: "SuccessfulOperation"
          x-uppercaseResponseId: "SUCCESSFUL_OPERATION"
          uppercase_operation_id: "ENCODE_WGS84"
        "405":
          description: "Invalid input"
          x-responseId: "InvalidInput"
          x-uppercaseResponseId: "INVALID_INPUT"
          uppercase_operation_id: "ENCODE_WGS84"
      operation_id: "encode_wgs84"
      uppercase_operation_id: "ENCODE_WGS84"
      path: "/wgs84/encode"
      PATH_ID: "WGS84_ENCODE"
      hasPathParams: false
      HttpMethod: "Post"
  /wgs84/decode:
    post:
      tags:
      - "Coordinates"
      summary: "WGS84 decode endpoint"
      description: "World Geodetic System 1984"
      operationId: "decodeWGS84"
      parameters: []
      responses:
        "200":
          description: "Successful operation"
          x-responseId: "SuccessfulOperation"
          x-uppercaseResponseId: "SUCCESSFUL_OPERATION"
          uppercase_operation_id: "DECODE_WGS84"
        "405":
          description: "Invalid input"
          x-responseId: "InvalidInput"
          x-uppercaseResponseId: "INVALID_INPUT"
          uppercase_operation_id: "DECODE_WGS84"
      operation_id: "decode_wgs84"
      uppercase_operation_id: "DECODE_WGS84"
      path: "/wgs84/decode"
      PATH_ID: "WGS84_DECODE"
      hasPathParams: false
      HttpMethod: "Post"
definitions:
  WGS84_encoded:
    type: "object"
    required:
    - "wgs84"
    properties:
      wgs84:
        type: "string"
        example: "A0 49 41 81 FF E8 B1 00 09 12 18 18 32"
    upperCaseName: "WGS84_ENCODED"
  WGS84_decoded:
    type: "object"
    required:
    - "latitude"
    - "longitude"
    properties:
      latitude:
        type: "number"
        format: "double"
        example: 12.2324125
        description: "from -90 to +90 [degrees]"
      longitude:
        type: "number"
        format: "double"
        example: 47.2324125
        description: "from -180 to +180 [degrees]"
      innerRadiuse:
        type: "number"
        format: "int32"
        example: 60.0
        description: "increment of 5 from 0 to 327 675 [meters]"
      uncertaintyRadiuse:
        type: "number"
        format: "int32"
        example: 20.0
        description: "from 0 to 1 800 000 [meters]"
      offsetAngle:
        type: "number"
        format: "int32"
        example: 50.0
        description: "increment of 2 from 0 to 359.9...9 [degrees]"
      includedAngle:
        type: "number"
        format: "int32"
        example: 30.0
        description: "increment of 2 from 0.0...1 to 360 [degrees]"
      confidence:
        type: "number"
        format: "int32"
        example: 90.0
    upperCaseName: "WGS84_DECODED"
