/* 
 * Cell Tower Geolocation
 *
 * This is a cell tower geolocation converter on the OpenAPI 3.0 specification.
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Wgs84Encoded {
  #[serde(rename = "wgs84")]
  wgs84: String
}

impl Wgs84Encoded {
  pub fn new(wgs84: String) -> Wgs84Encoded {
    Wgs84Encoded {
      wgs84: wgs84
    }
  }

  pub fn set_wgs84(&mut self, wgs84: String) {
    self.wgs84 = wgs84;
  }

  pub fn with_wgs84(mut self, wgs84: String) -> Wgs84Encoded {
    self.wgs84 = wgs84;
    self
  }

  pub fn wgs84(&self) -> &String {
    &self.wgs84
  }


}



